server:
  port: 8040
spring:
  application:
    name: microserivce-gateway-zuul
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@10.0.0.100:8761/eureka/,http://admin:admin123@10.0.0.100:8762/eureka/
  instance:
    prefer-ip-address: true  # \u8868\u793A\u5C06\u81EA\u5DF1\u7684ip\u6CE8\u518C\u5230Eureka Server\uFF1B\u4E0D\u914D\u6216\u914D\u7F6E\u4E3Afalse\u65F6\uFF0C\u8868\u793A\u6CE8\u518C\u8BE5\u5FAE\u670D\u52A1\u6240\u5728\u64CD\u4F5C\u7CFB\u7EDF\u7684hostname\u5230Eureka Server