server:
  port: 8010
spring:
  application:
    name: microserivce-consumer-movie-feign-hystrix
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@peer1:8761/eureka/,http://admin:admin123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true  # 表示将自己的ip注册到Eureka Server；不配或配置为false时，表示注册该微服务所在操作系统的hostname到Eureka Server
feign:
  hystrix:
    enabled: true
## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
