server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:                           # 指定数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    tomcat:
      default-auto-commit: true
      initial-size: 20
      max-active: 50
      min-idle: 10
      max-idle: 20
      max-wait: 10000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: select 1
      validation-interval: 30000
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin123@peer1:8761/eureka/,http://admin:admin123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true  # 表示将自己的ip注册到Eureka Server；不配或配置为false时，表示注册该微服务所在操作系统的hostname到Eureka Server
    metadata-map:
      my-metadate: 我自定义的元数据

## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@


