server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false     # 表示是否注册到Eureka Server，默认为true，由于当前应用就是Eureka Server，故设置为false
    fetchRegistry: false          # 表示是否从Eureka Server获取注册信息，默认为true，由于这是一个单点的Eureka Server，不需要同步其他Eureka Server节点的数据，故设置为false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  security:
    user:
      name: admin
      password: admin123
